// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ob5avIbNSusgqucSOEyNZpOO3dI8eF8',
    appId: '1:584322032495:web:1dde4f5472c270ac6ffe9a',
    messagingSenderId: '584322032495',
    projectId: 'calculator-30523',
    authDomain: 'calculator-30523.firebaseapp.com',
    storageBucket: 'calculator-30523.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN2Z5D95yhCx2tbw7LKHJZx6zaqe1aHvE',
    appId: '1:584322032495:android:00b06da777fbcff36ffe9a',
    messagingSenderId: '584322032495',
    projectId: 'calculator-30523',
    storageBucket: 'calculator-30523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBBOi1Mo_IRurfeGztOljHhNSIGJxA_B4',
    appId: '1:584322032495:ios:b13e327793c20d806ffe9a',
    messagingSenderId: '584322032495',
    projectId: 'calculator-30523',
    storageBucket: 'calculator-30523.appspot.com',
    iosBundleId: 'com.example.coffeeCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBBOi1Mo_IRurfeGztOljHhNSIGJxA_B4',
    appId: '1:584322032495:ios:b13e327793c20d806ffe9a',
    messagingSenderId: '584322032495',
    projectId: 'calculator-30523',
    storageBucket: 'calculator-30523.appspot.com',
    iosBundleId: 'com.example.coffeeCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ob5avIbNSusgqucSOEyNZpOO3dI8eF8',
    appId: '1:584322032495:web:cf2fcfbd522320f46ffe9a',
    messagingSenderId: '584322032495',
    projectId: 'calculator-30523',
    authDomain: 'calculator-30523.firebaseapp.com',
    storageBucket: 'calculator-30523.appspot.com',
  );

}